In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline
%precision 3

'%.3f'

In [22]:
df = pd.read_csv("../stat_analysis/data/ch4_scores400.csv")
scores = np.array(df["score"])
scores[:10]

array([76, 55, 80, 80, 74, 61, 81, 76, 23, 80])

In [23]:
np.random.choice([1, 2, 3], 3) #복원 추출: 중복 가능

array([3, 3, 2])

In [24]:
np.random.choice([1, 2, 3], 3, replace = False) #비복원 추출: 중복 불가

array([3, 1, 2])

In [25]:
np.random.seed(0) #랜덤 시드가 0이면 매번 같음
np.random.choice([1, 2, 3], 3)

array([1, 2, 1])

In [26]:
np.random.seed(0)
sample = np.random.choice(scores, 20) #표본 크기 20으로 복원 추출
sample.mean()

70.400

In [27]:
scores.mean()

69.530

In [28]:
for i in range(5):
    sample = np.random.choice(scores, 20)
    print(f"{i+1}번째 무작위 추출로 얻은 표본평균", sample.mean())

1번째 무작위 추출로 얻은 표본평균 72.45
2번째 무작위 추출로 얻은 표본평균 63.7
3번째 무작위 추출로 얻은 표본평균 66.05
4번째 무작위 추출로 얻은 표본평균 71.7
5번째 무작위 추출로 얻은 표본평균 74.15


In [29]:
dice = [1, 2, 3, 4, 5, 6]
prob = [1/21, 2/21, 3/21, 4/21, 5/21, 6/21]

In [30]:
num_trial = 100
sample = np.random.choice(dice, num_trial, p = prob)
sample

array([1, 4, 6, 4, 5, 5, 6, 6, 3, 5, 6, 5, 6, 6, 2, 3, 1, 6, 5, 6, 3, 4,
       5, 3, 4, 3, 5, 5, 4, 4, 6, 4, 6, 5, 6, 5, 4, 6, 2, 6, 4, 5, 3, 4,
       6, 5, 5, 5, 3, 4, 5, 4, 4, 6, 4, 4, 6, 6, 2, 2, 4, 5, 1, 6, 4, 3,
       2, 2, 6, 3, 5, 4, 2, 4, 4, 6, 6, 1, 5, 3, 6, 6, 4, 2, 1, 6, 4, 4,
       2, 4, 1, 3, 6, 6, 6, 4, 5, 4, 3, 3])

In [31]:
fig = plt.figure(figsize = (10, 6)) #계급폭을 1점으로 하는 히스토그램
ax = fig.add_subplot(111)
ax.hist(scores, bins = 100, range = (0, 100), density = True)
ax.set_xlim(20, 100)
ax.set_ylim(0, 0.042)
ax.set_xlabel("score")
ax.set_ylabel("relative frequency")

plt.show

<function matplotlib.pyplot.show(close=None, block=None)>

In [32]:
np.random.choice(scores)

np.int64(66)

In [33]:
sample = np.random.choice(scores, 10000)

fig = plt.figure(figsize = (10, 6))
ax = fig.add_subplot(111)
ax.hist(sample, bins = 100, range = (0, 100), density = True)
ax.set_xlim(20, 100)
ax.set_ylim(0, 0.042)
ax.set_xlabel("score")
ax.set_ylabel("relative frequency")

plt.show

<function matplotlib.pyplot.show(close=None, block=None)>

In [34]:
sample_means = [np.random.choice(scores, 20).mean() for _ in range(10000)]

fig = plt.figure(figsize = (10, 6))
ax = fig.add_subplot(111)
ax.hist(sample_means, bins = 100, range = (0, 100), density = True)
ax.vlines(np.mean(scores), 0, 1, "gray")
ax.set_xlim(50, 90)
ax.set_ylim(0, 0.13)
ax.set_xlabel("score")
ax.set_ylabel("relative frequency")

plt.show()

SyntaxError: positional argument follows keyword argument (692698692.py, line 5)